In [ ]:
from google.colab import files
uploaded = files.upload()

Saving data.txt to data.txt


In [ ]:
read_file = open("data.txt", "r").read()

In [ ]:
import re
import pandas as pd

file = re.sub("\s+", ",", read_file.strip())
readfile2 = file.split(',')
print(len(readfile2))

1126920


In [ ]:
def chunks(l, n):
    n = max(1, n)
    return (l[i:i+n] for i in range(0, len(l), n))

In [ ]:
a = list(chunks(readfile2, 10))
print(len(a))

112692


In [ ]:
a[50]

['112642',
 '"2020.01.05',
 '13:35:28"',
 '75',
 '17',
 '0',
 '9',
 '33.2',
 '33.2',
 '1']

In [ ]:
df = pd.DataFrame (a, columns = ['id','Date','Time','Air_Moisture','Air_Temp','Soil_Moisture','Soil_Temp', 'Lat', 'Long', 'Node'])
df.head

<bound method NDFrame.head of             id         Date       Time  ...        Lat       Long Node
0       112692  "2020.01.07  14:13:40"  ...       33.2       33.2    5
1       112691  "2020.01.07  14:13:26"  ...       33.2       33.2    9
2       112690  "2020.01.07  14:13:22"  ...       33.2       33.2    8
3       112689  "2020.01.07  14:13:08"  ...       33.2       33.2    2
4       112688  "2020.01.07  14:11:03"  ...       33.2       33.2    1
...        ...          ...        ...  ...        ...        ...  ...
112687       5  "2019.03.21  16:14:46"  ...  99.999999  99.999999    5
112688       4  "2019.03.21  16:14:46"  ...  99.999999  99.999999    4
112689       3  "2019.03.21  16:14:46"  ...  99.999999  99.999999    3
112690       2  "2019.03.21  16:14:46"  ...  99.999999  99.999999    2
112691       1  "2019.03.21  16:14:46"  ...  99.999999  99.999999    1

[112692 rows x 10 columns]>

In [ ]:
df = df.drop(columns=['id', 'Lat', 'Long', 'Node'])
df.head

<bound method NDFrame.head of                Date       Time Air_Moisture Air_Temp Soil_Moisture Soil_Temp
0       "2020.01.07  14:13:40"           91     13.5         78.21    10.125
1       "2020.01.07  14:13:26"           91     13.6        92.672     9.938
2       "2020.01.07  14:13:22"           91     13.6          81.2     9.875
3       "2020.01.07  14:13:08"           91     13.2        68.817    10.375
4       "2020.01.07  14:11:03"           91     13.2           100    10.313
...             ...        ...          ...      ...           ...       ...
112687  "2019.03.21  16:14:46"           21       22            21        11
112688  "2019.03.21  16:14:46"           21       22            21        43
112689  "2019.03.21  16:14:46"           21       22            33        12
112690  "2019.03.21  16:14:46"           21       22            25        26
112691  "2019.03.21  16:14:46"           21       22            23        24

[112692 rows x 6 columns]>

In [ ]:
df["Air_Moisture"] = pd.to_numeric(df["Air_Moisture"])
df["Air_Temp"] = pd.to_numeric(df["Air_Temp"])
df["Soil_Moisture"] = pd.to_numeric(df["Soil_Moisture"])
df["Soil_Temp"] = pd.to_numeric(df["Soil_Temp"])

df.dtypes

Date              object
Time              object
Air_Moisture     float64
Air_Temp         float64
Soil_Moisture    float64
Soil_Temp        float64
dtype: object

In [ ]:
df["Date"] = df['Date'].str.replace('\"','')
df["Time"] = df['Time'].str.replace('\"','')
df.head

<bound method NDFrame.head of               Date      Time  Air_Moisture  Air_Temp  Soil_Moisture  Soil_Temp
0       2020.01.07  14:13:40          91.0      13.5         78.210     10.125
1       2020.01.07  14:13:26          91.0      13.6         92.672      9.938
2       2020.01.07  14:13:22          91.0      13.6         81.200      9.875
3       2020.01.07  14:13:08          91.0      13.2         68.817     10.375
4       2020.01.07  14:11:03          91.0      13.2        100.000     10.313
...            ...       ...           ...       ...            ...        ...
112687  2019.03.21  16:14:46          21.0      22.0         21.000     11.000
112688  2019.03.21  16:14:46          21.0      22.0         21.000     43.000
112689  2019.03.21  16:14:46          21.0      22.0         33.000     12.000
112690  2019.03.21  16:14:46          21.0      22.0         25.000     26.000
112691  2019.03.21  16:14:46          21.0      22.0         23.000     24.000

[112692 rows x 6 colu

In [ ]:
df["Timestamp"] = df["Date"]+" "+df["Time"]
df = df.drop(columns=['Date', 'Time'])
df.head

<bound method NDFrame.head of         Air_Moisture  Air_Temp  Soil_Moisture  Soil_Temp            Timestamp
0               91.0      13.5         78.210     10.125  2020.01.07 14:13:40
1               91.0      13.6         92.672      9.938  2020.01.07 14:13:26
2               91.0      13.6         81.200      9.875  2020.01.07 14:13:22
3               91.0      13.2         68.817     10.375  2020.01.07 14:13:08
4               91.0      13.2        100.000     10.313  2020.01.07 14:11:03
...              ...       ...            ...        ...                  ...
112687          21.0      22.0         21.000     11.000  2019.03.21 16:14:46
112688          21.0      22.0         21.000     43.000  2019.03.21 16:14:46
112689          21.0      22.0         33.000     12.000  2019.03.21 16:14:46
112690          21.0      22.0         25.000     26.000  2019.03.21 16:14:46
112691          21.0      22.0         23.000     24.000  2019.03.21 16:14:46

[112692 rows x 5 columns]>

In [ ]:
df['Timestamp'] = df['Timestamp'].astype('str') 
df['Timestamp'] = pd.to_datetime(df['Timestamp'], format= "%Y%m%d %H:%M:%S")
df.dtypes

Air_Moisture            float64
Air_Temp                float64
Soil_Moisture           float64
Soil_Temp               float64
Timestamp        datetime64[ns]
dtype: object

In [ ]:
df = df.sort_values(by=['Timestamp'])
df.head

<bound method NDFrame.head of         Air_Moisture  Air_Temp  Soil_Moisture  Soil_Temp           Timestamp
112691          21.0      22.0         23.000     24.000 2019-03-21 16:14:46
112687          21.0      22.0         21.000     11.000 2019-03-21 16:14:46
112690          21.0      22.0         25.000     26.000 2019-03-21 16:14:46
112689          21.0      22.0         33.000     12.000 2019-03-21 16:14:46
112688          21.0      22.0         21.000     43.000 2019-03-21 16:14:46
...              ...       ...            ...        ...                 ...
4               91.0      13.2        100.000     10.313 2020-01-07 14:11:03
3               91.0      13.2         68.817     10.375 2020-01-07 14:13:08
2               91.0      13.6         81.200      9.875 2020-01-07 14:13:22
1               91.0      13.6         92.672      9.938 2020-01-07 14:13:26
0               91.0      13.5         78.210     10.125 2020-01-07 14:13:40

[112692 rows x 5 columns]>

In [ ]:
# df = df.dropna()
# df.head

In [ ]:
# df = df[~(df == 0).any(axis=1)]
# df.head

In [ ]:
# df = df.reset_index(drop=True)
# df.head

In [ ]:
original = df.copy()

Forecasting with frequency as minutes

In [ ]:
df = df.set_index(['Timestamp'], drop=True)
df = df.resample('T').mean()
df.head

<bound method NDFrame.head of                      Air_Moisture  Air_Temp  Soil_Moisture  Soil_Temp
Timestamp                                                            
2019-03-21 16:14:00          21.0    22.000       24.60000   23.20000
2019-03-21 16:15:00           NaN       NaN            NaN        NaN
2019-03-21 16:16:00           NaN       NaN            NaN        NaN
2019-03-21 16:17:00           NaN       NaN            NaN        NaN
2019-03-21 16:18:00           NaN       NaN            NaN        NaN
...                           ...       ...            ...        ...
2020-01-07 14:09:00           NaN       NaN            NaN        NaN
2020-01-07 14:10:00          91.0    13.300       81.79450   10.78150
2020-01-07 14:11:00          91.0    13.200      100.00000   10.31300
2020-01-07 14:12:00           NaN       NaN            NaN        NaN
2020-01-07 14:13:00          91.0    13.475       80.22475   10.07825

[420360 rows x 4 columns]>

In [ ]:
df = df.fillna(df.mean())
df.head

<bound method NDFrame.head of                      Air_Moisture   Air_Temp  Soil_Moisture  Soil_Temp
Timestamp                                                             
2019-03-21 16:14:00     21.000000  22.000000      24.600000  23.200000
2019-03-21 16:15:00     63.702282  23.737264      52.738325  18.103805
2019-03-21 16:16:00     63.702282  23.737264      52.738325  18.103805
2019-03-21 16:17:00     63.702282  23.737264      52.738325  18.103805
2019-03-21 16:18:00     63.702282  23.737264      52.738325  18.103805
...                           ...        ...            ...        ...
2020-01-07 14:09:00     63.702282  23.737264      52.738325  18.103805
2020-01-07 14:10:00     91.000000  13.300000      81.794500  10.781500
2020-01-07 14:11:00     91.000000  13.200000     100.000000  10.313000
2020-01-07 14:12:00     63.702282  23.737264      52.738325  18.103805
2020-01-07 14:13:00     91.000000  13.475000      80.224750  10.078250

[420360 rows x 4 columns]>

In [ ]:
train = df[:int(0.8*(len(df)))]
valid = df[int(0.8*(len(df))):]

#fit the model
from statsmodels.tsa.vector_ar.var_model import VAR

model = VAR(endog=train)
model_fit = model.fit()

# make prediction on validation
prediction = model_fit.forecast(model_fit.y, steps=len(valid))

/usr/local/lib/python3.6/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


In [ ]:
#Error calculation
from sklearn.metrics import mean_squared_error
import numpy as np
import math
cols = df.columns
pred = pd.DataFrame(index=range(0,len(prediction)),columns=[df.columns])
for j in range(0,4):
    for i in range(0, len(prediction)):
       pred.iloc[i][j] = prediction[i][j]
for i in range(len(cols)):
    print('rmse value for', cols[i], 'is : ', np.sqrt(mean_squared_error(pred.iloc[i], valid.iloc[i])))

rmse value for Air_Moisture is :  0.23428704128491268
rmse value for Air_Temp is :  0.30057936222260107
rmse value for Soil_Moisture is :  0.32199994450356867
rmse value for Soil_Temp is :  0.32946831288228023


In [ ]:
#make next 7hours prediction
model = VAR(endog=df)
model_fit = model.fit()
yhat = model_fit.forecast(model_fit.y, steps=7)
print(yhat)

[[83.76979944 15.61432536 78.21819194 11.60770658]
 [78.25925601 17.65207547 75.50560992 12.85418239]
 [73.91452954 19.31447283 73.04074072 13.97993006]
 [70.55826097 20.66002249 70.82232604 14.98474479]
 [68.02333671 21.74116106 68.8424816  15.87245887]
 [66.15803312 22.60396645 67.08865777 16.64965966]
 [64.82854829 23.2882543  65.54525801 17.32466709]]


/usr/local/lib/python3.6/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


Forcasting with frequency as hours.

In [ ]:
original = original.set_index(['Timestamp'], drop=True)
original = original.resample('h').mean()
original.head

<bound method NDFrame.head of                      Air_Moisture   Air_Temp  Soil_Moisture  Soil_Temp
Timestamp                                                             
2019-03-21 16:00:00     21.000000  22.000000      24.600000  23.200000
2019-03-21 17:00:00     38.666667  25.333333      50.500000        NaN
2019-03-21 18:00:00           NaN        NaN            NaN        NaN
2019-03-21 19:00:00           NaN        NaN            NaN        NaN
2019-03-21 20:00:00           NaN        NaN            NaN        NaN
...                           ...        ...            ...        ...
2020-01-07 10:00:00           NaN        NaN            NaN        NaN
2020-01-07 11:00:00           NaN        NaN            NaN        NaN
2020-01-07 12:00:00     89.944444  12.433333      78.750833   9.104444
2020-01-07 13:00:00           NaN        NaN            NaN        NaN
2020-01-07 14:00:00     90.647059  13.147059      76.396059   9.643588

[7007 rows x 4 columns]>

In [ ]:
original = original.fillna(original.mean())
original.head

<bound method NDFrame.head of                      Air_Moisture   Air_Temp  Soil_Moisture  Soil_Temp
Timestamp                                                             
2019-03-21 16:00:00     21.000000  22.000000      24.600000  23.200000
2019-03-21 17:00:00     38.666667  25.333333      50.500000  19.646274
2019-03-21 18:00:00     59.195159  26.756062      45.725832  19.646274
2019-03-21 19:00:00     59.195159  26.756062      45.725832  19.646274
2019-03-21 20:00:00     59.195159  26.756062      45.725832  19.646274
...                           ...        ...            ...        ...
2020-01-07 10:00:00     59.195159  26.756062      45.725832  19.646274
2020-01-07 11:00:00     59.195159  26.756062      45.725832  19.646274
2020-01-07 12:00:00     89.944444  12.433333      78.750833   9.104444
2020-01-07 13:00:00     59.195159  26.756062      45.725832  19.646274
2020-01-07 14:00:00     90.647059  13.147059      76.396059   9.643588

[7007 rows x 4 columns]>

In [ ]:
train = original[:int(0.8*(len(original)))]
valid = original[int(0.8*(len(original))):]

#fit the model

model = VAR(endog=train)
model_fit = model.fit()

# make prediction on validation
prediction = model_fit.forecast(model_fit.y, steps=len(valid))

#Error calculation
cols = original.columns
pred = pd.DataFrame(index=range(0,len(prediction)),columns=[cols])
for j in range(0,4):
    for i in range(0, len(prediction)):
       pred.iloc[i][j] = prediction[i][j]
for i in range(len(cols)):
    print('rmse value for', cols[i], 'is : ', np.sqrt(mean_squared_error(pred.iloc[i], valid.iloc[i])))

#make next 7 days prediction
model = VAR(endog=df)
model_fit = model.fit()
yhat = model_fit.forecast(model_fit.y, steps=7)
print(yhat)

/usr/local/lib/python3.6/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)


rmse value for Air_Moisture is :  0.18776183078519568
rmse value for Air_Temp is :  0.30401100701123196
rmse value for Soil_Moisture is :  0.3802036390246619
rmse value for Soil_Temp is :  0.4332765750788156
[[79.40331746 18.09510859 63.28773632 14.01125371]
 [72.67836312 20.61585075 57.14063783 15.9887352 ]
 [68.80273719 22.01315458 54.73247973 16.99725274]
 [66.58683068 22.78743086 53.70832257 17.51883579]
 [65.3281337  23.214886   53.23675881 17.79190391]
 [64.61656428 23.45014201 53.00440569 17.93632746]
 [64.21563643 23.57939996 52.88389522 18.01335046]]


/usr/local/lib/python3.6/dist-packages/statsmodels/base/wrapper.py:35: FutureWarning: y is a deprecated alias for endog, will be removed in version 0.11.0
  obj = getattr(results, attr)
